language: haskell
ghc: 7.8
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cabal update
  - cabal install cabal-install
script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
  - cabal install stylish-haskell
  - cabal install hlint
  - ./acceptance-tests

